github.com:
    users:
        tharunmandava:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: tharunmandava
